[general]
live_config_reload = true 
import = ["~/.config/alacritty/gruvbox_dark.toml"]

[window]
opacity = 1.0
blur = false

[font]
normal = { family = "FiraCode", style = "Regular" }
bold = { family = "FiraCode", style = "Bold" }



